<c:set var="SERVLET_PATH" value="${pageContext.request.contextPath}"/>
<c:set var="IMG_PATH" value="../images"/>
<c:set var="CSS_PATH" value="../css"/>
<c:set var="JS_PATH" value="../js"/>
<c:set var="dateType" value="yyyy-MM-dd"/>
<c:set var="dateTimeType" value="yyyy-MM-dd HH:mm:ss"/>
<c:set var="moneyType" value="##,###,###,###,##0.00"/>
<c:set var="sl1Type" value="###,###,##0"/>
<c:set var="sl2Type" value="###,###,##0.000###"/>

