<script type="text/javascript" src="${JS_PATH}/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="${JS_PATH}/jquery.form.js"></script>
<script type="text/javascript" src="${JS_PATH}/jquery.alerts.js"></script>
<script type="text/javascript" src="${JS_PATH}/commonUtils.js"></script>
<script type="text/javascript" src="${JS_PATH}/numberFormat.js"></script>
<script type="text/javascript" src="${SERVLET_PATH}/dwr/engine.js"></script>  
<script type="text/javascript" src="${SERVLET_PATH}/dwr/util.js"></script>

