<script type="text/javascript" src="${JS_PATH}/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<c:url value='/js/lhgdialog/lhgdialog.min.js'></c:url>"></script>
<script type="text/javascript" src="${JS_PATH}/jquery.form.js"></script>
<script type="text/javascript" src="${JS_PATH}/jquery.alerts.js"></script>
<script type="text/javascript" src="${JS_PATH}/commonUtils.js"></script>
<script type="text/javascript" src="${JS_PATH}/numberFormat.js"></script>
<script type="text/javascript" src="${SERVLET_PATH}/dwr/engine.js"></script>  
<script type="text/javascript" src="${SERVLET_PATH}/dwr/util.js"></script>
<script type="text/javascript">
var api = frameElement.api, W = api.opener;
</script>


